<?php

if(function_exists("register_field_group"))
{
	register_field_group(array (
		'id' => 'acf_medverkande-aktorer',
		'title' => 'Medverkande aktorer',
		'fields' => array (
			array (
				'key' => 'field_5551a0fa0381c',
				'label' => 'Rubrik',
				'name' => 'rubrik',
				'type' => 'text',
				'instructions' => 'Ange rubrik',
				'required' => 1,
				'default_value' => 'Aktör på Hamnfestivalen?',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5551a1500381d',
				'label' => 'Datum',
				'name' => 'datum',
				'type' => 'text',
				'instructions' => 'Ange datum för Hamnfestivalen',
				'required' => 1,
				'default_value' => '30 juli – 2 augusti 2015',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5551a1710381e',
				'label' => 'Introtext',
				'name' => 'introtext',
				'type' => 'textarea',
				'instructions' => 'Ange introduktionstext',
				'required' => 1,
				'default_value' => 'Hamnfestivalen bjuder på fyra festfyllda dagar med upplevelser, musik, mat & kultur. I juli 2014 slog portarna upp till en fantastisk Hamnfestival som arrangerades längs havet i Limhamn. Hamnfestivalen 2014 drog över 15000 besökare och succén var omedelbar. Årets Hamnfestival går av stapeln den 30 juli och pågår t.om. den 2 augusti.
	
	Är du intresserad av att bli en medverkande aktör på Hamnfestivalen?',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5551a1ea03820',
				'label' => 'E-post',
				'name' => 'e-post',
				'type' => 'text',
				'instructions' => 'Ange e-postadress dit anmälan ska skickas',
				'required' => 1,
				'default_value' => 'info@polimhamn.se',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5551a2cd1ce63',
				'label' => 'Krav för anmälan',
				'name' => 'krav_for_anmalan',
				'type' => 'textarea',
				'instructions' => 'Ange krav för anmälan',
				'required' => 1,
				'default_value' => 'Tänk på att anmälan sker omgående och är bindande.
	
	Krav på medverkan samtliga dagar. Avtal kommer skrivas med samtliga aktörer. Mer praktisk information delges vid avtalsskrivningen. Bodar och marknadsstånd finns på plats till ert förfogande. Bodarna är till för våra mataktörer och finns i begränsat antal. Övriga aktörer har tillgång till moderna marknadsstånd som har en exponeringsyta på 220x80cm.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5551a2f81ce64',
				'label' => 'Plats och öppettider',
				'name' => 'plats_och_oppettider',
				'type' => 'textarea',
				'instructions' => 'Ange information kring plats och öppettider för Hamnfestivalen',
				'required' => 1,
				'default_value' => 'Årets Hamnfestival är primärt förlagd i och kring Småbåtshamnen och Fiskehamnen. Fiskehamnen håller öppet för besökare mellan kl 11.00 – 20.00 alla dagar och Småbåtshamnen mellan kl. 11.00 – 22.00 alla dagar.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5551a3301ce65',
				'label' => 'Pris för matstånd',
				'name' => 'pris_for_matstand',
				'type' => 'text',
				'instructions' => 'Ange pris för matstånd',
				'required' => 1,
				'default_value' => '2800 kr ex. moms',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5551a37a1ce66',
				'label' => 'Pris för försäljning',
				'name' => 'pris_for_forsaljning',
				'type' => 'text',
				'instructions' => 'Ange pris för övrig försäljningsstånd',
				'required' => 1,
				'default_value' => '2000 kr exkl. moms',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5551a3f71ce67',
				'label' => 'Avtal aktiviteter',
				'name' => 'avtal_aktiviteter',
				'type' => 'file',
				'required' => 1,
				'save_format' => 'url',
				'library' => 'uploadedTo',
			),
			array (
				'key' => 'field_5551a4721ce68',
				'label' => 'Avtal mat',
				'name' => 'avtal_mat',
				'type' => 'file',
				'required' => 1,
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_5551a4841ce69',
				'label' => 'Avtal försäljning',
				'name' => 'avtal_forsaljning',
				'type' => 'file',
				'required' => 1,
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_5551a4931ce6a',
				'label' => 'Avtal el',
				'name' => 'avtal_el',
				'type' => 'file',
				'required' => 1,
				'save_format' => 'url',
				'library' => 'all',
			),
			array (
				'key' => 'field_5551a4a71ce6b',
				'label' => 'Arrangör',
				'name' => 'arrangor',
				'type' => 'textarea',
				'instructions' => 'Ange arrangör',
				'required' => 1,
				'default_value' => 'PÅ LIMHAMN ek. förening
	Gitte Knutsson, Verksamhetsledare',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
			array (
				'key' => 'field_5551a50d1ce6c',
				'label' => 'Arrangör telefonnummer',
				'name' => 'arrangor_telefonnummer',
				'type' => 'text',
				'instructions' => 'Ange arrangörens telefonnummer',
				'required' => 1,
				'default_value' => '0760-104405',
				'placeholder' => '',
				'prepend' => '',
				'append' => '',
				'formatting' => 'html',
				'maxlength' => '',
			),
			array (
				'key' => 'field_5551a5261ce6d',
				'label' => 'Marknadsförs i',
				'name' => 'marknadsfors_i',
				'type' => 'textarea',
				'instructions' => 'Ange text om var arrangemanget marknadsförs',
				'required' => 1,
				'default_value' => 'Sydsvenskan, Magasin Limhamn, Malmö stads hemsida, www.polimhamn.se, sociala medier, affischer och andra lokala medier, pressbearbetning samt viss marknadsföring i Danmark.',
				'placeholder' => '',
				'maxlength' => '',
				'rows' => '',
				'formatting' => 'br',
			),
		),
		'location' => array (
			array (
				array (
					'param' => 'page_template',
					'operator' => '==',
					'value' => 'medverkande_aktorer.php',
					'order_no' => 0,
					'group_no' => 0,
				),
			),
		),
		'options' => array (
			'position' => 'normal',
			'layout' => 'no_box',
			'hide_on_screen' => array (
				0 => 'the_content',
				1 => 'excerpt',
				2 => 'discussion',
				3 => 'comments',
				4 => 'format',
				5 => 'featured_image',
				6 => 'categories',
				7 => 'tags',
				8 => 'send-trackbacks',
			),
		),
		'menu_order' => 0,
	));
}



?>